# -*- coding: utf-8 -*-
"""MLB_LINEBOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_Q9MVF3UUvlMxofCUEtziK60-qVdDNf
"""

pip install -q "opentelemetry-sdk==1.38.0" \
                "opentelemetry-api==1.38.0" \
                "opentelemetry-exporter-otlp-proto-grpc==1.38.0"

pip install -q chromadb sentence-transformers flask requests pypdf

import os
import re
import glob
import warnings
import hmac
import base64
import hashlib
import json
import numpy as np
import pandas as pd
import chromadb
import requests

from flask import Flask, request, abort
from sentence_transformers import SentenceTransformer

warnings.filterwarnings("ignore")
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# 可改設定
BOT_NAME = "⚾ Fantasy 球探助理"
BOT_ROLE = "MLB Fantasy 分析助理，幫您分析 2025 年的選手數據。"
BOT_STYLE = "直接根據上傳的 2025 數據回答，不顯示引用片段，無法判斷時不亂猜。"

CHUNK_SIZE = 380
CHUNK_OVERLAP = 80
TOP_K = 6
FINAL_REFERENCES = 2
#multilingual embedding
EMBED_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
CHROMA_DIR = "chroma_store"
COLLECTION_NAME = "mlb_fantasy_chunks"

# 固定 CSV 檔名
# 之後部署時，請把這兩個檔案放在和 app.py 同一層資料夾
HITTER_FILE = "hitters.csv"
PITCHER_FILE = "pitchers.csv"

if not os.path.exists(HITTER_FILE):
    raise FileNotFoundError(f"找不到檔案：{HITTER_FILE}")

if not os.path.exists(PITCHER_FILE):
    raise FileNotFoundError(f"找不到檔案：{PITCHER_FILE}")

# 讀取資料與清理
def infer_csv_role(df):
    cols = set(df.columns)
    if {"p_era", "p_win", "p_loss"} & cols:
        return "pitcher"
    return "hitter"

hitters = pd.read_csv(HITTER_FILE).copy()
pitchers = pd.read_csv(PITCHER_FILE).copy()

# 保險：如果兩個檔案放反了，自動交換
if infer_csv_role(hitters) == "pitcher" and infer_csv_role(pitchers) == "hitter":
    hitters, pitchers = pitchers, hitters

required_hitter_cols = [
    "last_name, first_name", "year", "pa", "home_run",
    "batting_avg", "on_base_plus_slg", "woba", "xwoba"
]
required_pitcher_cols = [
    "last_name, first_name", "year", "pa", "p_era",
    "k_percent", "bb_percent", "woba", "xwoba"
]

for col in required_hitter_cols:
    if col not in hitters.columns:
        raise ValueError(f"打者資料缺少欄位：{col}")

for col in required_pitcher_cols:
    if col not in pitchers.columns:
        raise ValueError(f"投手資料缺少欄位：{col}")

for df in [hitters, pitchers]:
    for col in df.columns:
        if col not in ["last_name, first_name"]:
            df[col] = pd.to_numeric(df[col], errors="ignore")

MIN_HITTER_PA = 100
if "pa" in hitters.columns:
    hitters["pa"] = pd.to_numeric(hitters["pa"], errors="coerce")
    hitters = hitters[hitters["pa"].fillna(0) >= MIN_HITTER_PA].copy()

AVAILABLE_YEARS = sorted(
    set(pd.to_numeric(hitters["year"], errors="coerce").dropna().astype(int).tolist()) |
    set(pd.to_numeric(pitchers["year"], errors="coerce").dropna().astype(int).tolist())
)

# 基礎工具
def safe_float(x):
    try:
        if pd.isna(x):
            return np.nan
        return float(x)
    except Exception:
        return np.nan


def fmt_num(x, digits=3):
    x = safe_float(x)
    if np.isnan(x):
        return "N/A"

    if digits <= 0:
        return str(int(round(x)))

    return f"{x:.{digits}f}".rstrip("0").rstrip(".")


def normalize_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9一-鿿]", "", text)
    return text


def zscore(series, higher_better=True):
    s = pd.to_numeric(series, errors="coerce")
    mean = s.mean()
    std = s.std()

    if std == 0 or pd.isna(std):
        z = pd.Series([0] * len(s), index=s.index)
    else:
        z = (s - mean) / std

    return z if higher_better else -z


def label_from_score(score):
    if score >= 1.0:
        return "非常高"
    elif score >= 0.3:
        return "偏高"
    elif score >= -0.3:
        return "中等"
    elif score >= -1.0:
        return "偏低"
    else:
        return "很低"


def player_aliases(name):
    if pd.isna(name):
        return []

    name = str(name).strip()
    aliases = {name}

    if "," in name:
        last, first = [x.strip() for x in name.split(",", 1)]
        aliases.add(f"{first} {last}")
        aliases.add(f"{first}{last}")
        aliases.add(f"{last}{first}")

    return [normalize_text(x) for x in aliases if x]

# 建立 fantasy 綜合分數
def weighted_z(df, col, weight=1.0, higher_better=True):
    if col not in df.columns:
        return pd.Series(0.0, index=df.index)
    return weight * zscore(df[col], higher_better)

hitters["fantasy_score"] = (
    weighted_z(hitters, "xwoba", 1.0, True)
    + weighted_z(hitters, "woba", 1.0, True)
    + weighted_z(hitters, "home_run", 0.9, True)
    + weighted_z(hitters, "barrel_batted_rate", 0.8, True)
    + weighted_z(hitters, "hard_hit_percent", 0.8, True)
    + weighted_z(hitters, "sweet_spot_percent", 0.5, True)
    + weighted_z(hitters, "bb_percent", 0.5, True)
    + weighted_z(hitters, "k_percent", 0.5, False)
    + weighted_z(hitters, "avg_hyper_speed", 0.4, True)
    + weighted_z(hitters, "whiff_percent", 0.4, False)
)

pitchers["fantasy_score"] = (
    weighted_z(pitchers, "xwoba", 1.0, False)
    + weighted_z(pitchers, "woba", 1.0, False)
    + weighted_z(pitchers, "p_era", 0.9, False)
    + weighted_z(pitchers, "barrel_batted_rate", 0.8, False)
    + weighted_z(pitchers, "hard_hit_percent", 0.8, False)
    + weighted_z(pitchers, "sweet_spot_percent", 0.5, False)
    + weighted_z(pitchers, "bb_percent", 0.6, False)
    + weighted_z(pitchers, "k_percent", 0.8, True)
    + weighted_z(pitchers, "whiff_percent", 0.6, True)
)

# 把每位球員轉成文件，再做分片
def safe_year(x, default=2025):
    try:
        if pd.isna(x):
            return default
        return int(float(x))
    except Exception:
        return default


def hitter_row_to_text(row):
    year = safe_year(row.get("year", np.nan))
    name = row.get("last_name, first_name", "Unknown")

    return f"""
球員: {name}
類型: hitter
年份: {year}
打席 PA: {fmt_num(row.get('pa', np.nan), 0)}
全壘打 HR: {fmt_num(row.get('home_run', np.nan), 0)}
打擊率 AVG: {fmt_num(row.get('batting_avg', np.nan), 3)}
OPS: {fmt_num(row.get('on_base_plus_slg', np.nan), 3)}
wOBA: {fmt_num(row.get('woba', np.nan), 3)}
xwOBA: {fmt_num(row.get('xwoba', np.nan), 3)}
Barrel%: {fmt_num(row.get('barrel_batted_rate', np.nan), 3)}
Hard Hit%: {fmt_num(row.get('hard_hit_percent', np.nan), 3)}
Sweet Spot%: {fmt_num(row.get('sweet_spot_percent', np.nan), 3)}
K%: {fmt_num(row.get('k_percent', np.nan), 3)}
BB%: {fmt_num(row.get('bb_percent', np.nan), 3)}
Whiff%: {fmt_num(row.get('whiff_percent', np.nan), 3)}
Fantasy Score: {fmt_num(row.get('fantasy_score', np.nan), 3)}
簡短描述: {name} 在 {year} 年的打擊資料，可用來分析長打、上壘能力、擊球品質與 fantasy 價值。
""".strip()


def pitcher_row_to_text(row):
    year = safe_year(row.get("year", np.nan))
    name = row.get("last_name, first_name", "Unknown")

    return f"""
球員: {name}
類型: pitcher
年份: {year}
面對打席 PA: {fmt_num(row.get('pa', np.nan), 0)}
ERA: {fmt_num(row.get('p_era', np.nan), 3)}
K%: {fmt_num(row.get('k_percent', np.nan), 3)}
BB%: {fmt_num(row.get('bb_percent', np.nan), 3)}
wOBA: {fmt_num(row.get('woba', np.nan), 3)}
xwOBA: {fmt_num(row.get('xwoba', np.nan), 3)}
Barrel%: {fmt_num(row.get('barrel_batted_rate', np.nan), 3)}
Hard Hit%: {fmt_num(row.get('hard_hit_percent', np.nan), 3)}
Sweet Spot%: {fmt_num(row.get('sweet_spot_percent', np.nan), 3)}
Whiff%: {fmt_num(row.get('whiff_percent', np.nan), 3)}
Fantasy Score: {fmt_num(row.get('fantasy_score', np.nan), 3)}
簡短描述: {name} 在 {year} 年的投球資料，可用來分析壓制能力、三振能力、控球與 fantasy 價值。
""".strip()


def chunk_text(text, chunk_size=380, overlap=80):
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])

        if end >= len(text):
            break

        start = end - overlap

    return chunks


documents = []

for _, row in hitters.iterrows():
    documents.append({
        "player": row["last_name, first_name"],
        "role": "hitter",
        "year": safe_year(row.get("year", np.nan)),
        "text": hitter_row_to_text(row),
        "home_run": safe_float(row.get("home_run", np.nan)),
        "fantasy_score": safe_float(row.get("fantasy_score", np.nan)),
    })

for _, row in pitchers.iterrows():
    documents.append({
        "player": row["last_name, first_name"],
        "role": "pitcher",
        "year": safe_year(row.get("year", np.nan)),
        "text": pitcher_row_to_text(row),
        "home_run": safe_float(row.get("home_run", np.nan)),
        "fantasy_score": safe_float(row.get("fantasy_score", np.nan)),
    })

all_chunks = []
all_metadatas = []

for item in documents:
    chunks = chunk_text(item["text"], CHUNK_SIZE, CHUNK_OVERLAP)
    for i, chunk in enumerate(chunks):
        all_chunks.append(chunk)
        all_metadatas.append({
            "player": item["player"],
            "role": item["role"],
            "year": item["year"],
            "chunk_index": i,
        })

# 建立 Embedding + Chroma 向量資料庫
embed_model = SentenceTransformer(EMBED_MODEL_NAME)
embeddings = embed_model.encode(
    all_chunks,
    convert_to_numpy=True,
    show_progress_bar=False
)

# 用記憶體版 Chroma，避免 Colab / 本機環境的一些 sqlite 問題
client = chromadb.EphemeralClient()

try:
    client.delete_collection(COLLECTION_NAME)
except Exception:
    pass

collection = client.create_collection(
    name=COLLECTION_NAME,
    metadata={"hnsw:space": "cosine"}
)

ids = [f"chunk_{i}" for i in range(len(all_chunks))]

collection.add(
    ids=ids,
    documents=all_chunks,
    embeddings=embeddings.tolist(),
    metadatas=all_metadatas,
)

# 問題解析與安全回答
from collections import Counter

DEFAULT_YEAR = AVAILABLE_YEARS[-1] if AVAILABLE_YEARS else 2025
SUPPORTED_YEARS = set(AVAILABLE_YEARS) if AVAILABLE_YEARS else {DEFAULT_YEAR}

STAT_CANDIDATES = [
    {"role":"hitter","col":"home_run","label":"HR","descending":True,"aliases":["全壘打","hr","home run","homer","最多全壘打"]},
    {"role":"hitter","col":"on_base_plus_slg","label":"OPS","descending":True,"aliases":["ops"]},
    {"role":"hitter","col":"batting_avg","label":"AVG","descending":True,"aliases":["打擊率","打率","avg"]},
    {"role":"hitter","col":"on_base_percent","label":"OBP","descending":True,"aliases":["上壘率","obp"]},
    {"role":"hitter","col":"slg_percent","label":"SLG","descending":True,"aliases":["長打率","slg"]},
    {"role":"hitter","col":"b_rbi","label":"RBI","descending":True,"aliases":["打點","rbi"]},
    {"role":"hitter","col":"r_total_stolen_base","label":"SB","descending":True,"aliases":["盜壘","盜壘數","sb"]},
    {"role":"hitter","col":"r_run","label":"R","descending":True,"aliases":["得分","runs"]},
    {"role":"hitter","col":"woba","label":"wOBA","descending":True,"aliases":["woba"]},
    {"role":"hitter","col":"xwoba","label":"xwOBA","descending":True,"aliases":["xwoba"]},
    {"role":"hitter","col":"fantasy_score","label":"Fantasy Score","descending":True,"aliases":["fantasy score","幻想分","綜合價值"]},

    {"role":"pitcher","col":"p_era","label":"ERA","descending":False,"aliases":["era","防禦率"]},
    {"role":"pitcher","col":"p_win","label":"W","descending":True,"aliases":["勝投","勝場","wins","win"]},
    {"role":"pitcher","col":"p_loss","label":"L","descending":False,"aliases":["敗投","敗場","losses","loss"]},
    {"role":"pitcher","col":"k_percent","label":"K%","descending":True,"aliases":["k%","三振率","k rate"]},
    {"role":"pitcher","col":"bb_percent","label":"BB%","descending":False,"aliases":["bb%","保送率"]},
    {"role":"pitcher","col":"whiff_percent","label":"Whiff%","descending":True,"aliases":["whiff","揮空率"]},
    {"role":"pitcher","col":"groundballs_percent","label":"GB%","descending":True,"aliases":["gb%","滾地球率"]},
    {"role":"pitcher","col":"xwoba","label":"xwOBA allowed","descending":False,"aliases":["xwoba allowed","預期被打擊表現"]},
    {"role":"pitcher","col":"fantasy_score","label":"Fantasy Score","descending":True,"aliases":["fantasy score","幻想分","綜合價值"]},
]

UNSUPPORTED_PATTERNS = [
    r"受傷", r"傷兵", r"交易", r"新聞", r"今天", r"明天", r"先發",
    r"最新", r"即時", r"合約", r"預測", r"賽程"
]

def build_metric_catalog():
    catalog = []

    for item in STAT_CANDIDATES:
        df = hitters if item["role"] == "hitter" else pitchers
        if item["col"] not in df.columns:
            continue

        new_item = dict(item)

        aliases = set()
        for x in item["aliases"]:
            nx = normalize_text(x)
            if len(nx) >= 2:
                aliases.add(nx)

        label_alias = normalize_text(item["label"])
        if len(label_alias) >= 2:
            aliases.add(label_alias)

        col_alias = normalize_text(item["col"])
        if len(col_alias) >= 2:
            aliases.add(col_alias)

        new_item["aliases"] = sorted(aliases, key=len, reverse=True)
        catalog.append(new_item)

    return catalog

METRIC_CATALOG = build_metric_catalog()

def extract_metric(query):
    q = normalize_text(query)
    best = None
    best_len = 0

    for item in METRIC_CATALOG:
        for alias in item["aliases"]:
            if alias and alias in q and len(alias) > best_len:
                best = item
                best_len = len(alias)

    return best

def extract_year(query):
    m = re.search(r"(20\d{2})", str(query))
    return int(m.group(1)) if m else None

def build_name_variants(df):
    names = df["last_name, first_name"].fillna("").astype(str).unique()

    first_counter = Counter()
    last_counter = Counter()

    for name in names:
        parts = [p.strip() for p in name.split(",")]
        if len(parts) == 2:
            last_name = normalize_text(parts[0])
            first_name = normalize_text(parts[1])
            if first_name:
                first_counter[first_name] += 1
            if last_name:
                last_counter[last_name] += 1

    name_map = {}

    for name in names:
        parts = [p.strip() for p in name.split(",")]
        variants = {normalize_text(name)}

        if len(parts) == 2:
            last_name = normalize_text(parts[0])
            first_name = normalize_text(parts[1])

            variants |= {
                f"{first_name}{last_name}",
                f"{last_name}{first_name}",
                f"{first_name} {last_name}",
                f"{last_name} {first_name}",
            }

            # 只有在名字本身夠長且不重複時，才加入單獨 first / last name
            if first_name and len(first_name) >= 4 and first_counter[first_name] == 1:
                variants.add(first_name)
            if last_name and len(last_name) >= 4 and last_counter[last_name] == 1:
                variants.add(last_name)

        name_map[name] = sorted(
            [v for v in variants if v],
            key=len,
            reverse=True
        )

    return name_map

HITTER_NAME_MAP = build_name_variants(hitters)
PITCHER_NAME_MAP = build_name_variants(pitchers)

def find_player(query):
    q = normalize_text(query)
    best = None
    best_len = 0

    for role, name_map in [("hitter", HITTER_NAME_MAP), ("pitcher", PITCHER_NAME_MAP)]:
        for name, variants in name_map.items():
            for v in variants:
                if v and v in q and len(v) > best_len:
                    best = (role, name)
                    best_len = len(v)
                    break

    return best

def extract_top_n(query):
    q = normalize_text(query)

    m = re.search(r"(?:top|前)(\d+)", q)
    if m:
        return max(1, min(int(m.group(1)), 20))

    zh_map = {
        "一":1, "二":2, "三":3, "四":4, "五":5,
        "六":6, "七":7, "八":8, "九":9, "十":10, "兩":2
    }
    m = re.search(r"前([一二三四五六七八九十兩])", q)
    if m:
        return zh_map[m.group(1)]

    if any(k in q for k in ["王", "第一", "最多", "最高", "最好", "最強", "最少", "最低"]):
        return 1

    return None

def is_analysis_question(query):
    q = normalize_text(query)
    return any(k in q for k in ["價值", "優點", "強在哪", "分析", "推薦", "值得", "特色", "為什麼", "評價"])

def is_unsupported_question(query):
    q = normalize_text(query)
    return any(re.search(p, q) for p in UNSUPPORTED_PATTERNS)

def get_player_row(role, name, year=DEFAULT_YEAR):
    df = hitters if role == "hitter" else pitchers

    year_series = pd.to_numeric(df["year"], errors="coerce")
    matched = df[(df["last_name, first_name"] == name) & (year_series == year)]

    if matched.empty:
        matched = df[df["last_name, first_name"] == name]

    if matched.empty:
        return None

    return matched.sort_values("year", ascending=False).iloc[0]

def rank_dataframe(metric, year=DEFAULT_YEAR):
    df = hitters.copy() if metric["role"] == "hitter" else pitchers.copy()

    if "year" in df.columns:
        year_series = pd.to_numeric(df["year"], errors="coerce")
        df = df[year_series == year].copy()

    return df

def answer_ranking(metric, top_n, year=DEFAULT_YEAR):
    df = rank_dataframe(metric, year=year)
    col = metric["col"]
    label = metric["label"]

    if df.empty or col not in df.columns:
        return f"我目前可分析的年份有：{', '.join(map(str, AVAILABLE_YEARS))}。"

    ranked = df.dropna(subset=[col]).sort_values(
        col,
        ascending=not metric["descending"]
    ).head(top_n)

    if ranked.empty:
        return f"我目前可分析的年份有：{', '.join(map(str, AVAILABLE_YEARS))}。"

    integer_cols = {"home_run", "b_rbi", "r_total_stolen_base", "r_run", "p_win", "p_loss"}

    if top_n == 1:
        row = ranked.iloc[0]
        value = fmt_num(row[col], 0 if col in integer_cols else 3)
        return f"{year} {label} 第一名是 {row['last_name, first_name']}，{label} = {value}。"

    lines = []
    for i, (_, row) in enumerate(ranked.iterrows(), start=1):
        value = fmt_num(row[col], 0 if col in integer_cols else 3)
        lines.append(f"{i}. {row['last_name, first_name']} — {label} {value}")

    return "\n".join(lines)

def answer_player_metric(role, name, metric, year=DEFAULT_YEAR):
    if role != metric["role"]:
        return "請把問題改成打者問打者指標，投手問投手指標。"

    row = get_player_row(role, name, year=year)
    if row is None:
        return "請直接輸入完整球員名字，像是 Judge, Aaron。"

    integer_cols = {"home_run", "b_rbi", "r_total_stolen_base", "r_run", "p_win", "p_loss"}
    value = fmt_num(row.get(metric["col"], np.nan), 0 if metric["col"] in integer_cols else 3)

    return f"{name} 的 {year} {metric['label']} 是 {value}。"

def answer_player_analysis(role, name, year=DEFAULT_YEAR):
    row = get_player_row(role, name, year=year)
    if row is None:
        return "請直接輸入完整球員名字，像是 Judge, Aaron。"

    if role == "hitter":
        parts = [
            f"OPS {fmt_num(row.get('on_base_plus_slg', np.nan), 3)}",
            f"HR {fmt_num(row.get('home_run', np.nan), 0)}",
            f"AVG {fmt_num(row.get('batting_avg', np.nan), 3)}",
            f"RBI {fmt_num(row.get('b_rbi', np.nan), 0)}",
            f"SB {fmt_num(row.get('r_total_stolen_base', np.nan), 0)}",
            f"xwOBA {fmt_num(row.get('xwoba', np.nan), 3)}",
        ]
        parts = [x for x in parts if not x.endswith("N/A")]
        return f"{name} 在 {year} 的打者價值主要看 {', '.join(parts[:4])}。"

    parts = [
        f"ERA {fmt_num(row.get('p_era', np.nan), 3)}",
        f"W {fmt_num(row.get('p_win', np.nan), 0)}",
        f"K% {fmt_num(row.get('k_percent', np.nan), 3)}",
        f"Whiff% {fmt_num(row.get('whiff_percent', np.nan), 3)}",
        f"xwOBA allowed {fmt_num(row.get('xwoba', np.nan), 3)}",
    ]
    parts = [x for x in parts if not x.endswith("N/A")]
    return f"{name} 在 {year} 的投手價值主要看 {', '.join(parts[:4])}。"

def answer_question(query):
    query = str(query).strip()

    if not query:
        return f"我是一個專門分析 MLB Fantasy 打者與投手的助理。幫您分析 {DEFAULT_YEAR} 年的選手數據。"

    year = extract_year(query) or DEFAULT_YEAR

    if year not in SUPPORTED_YEARS:
        return f"我目前可分析的年份有：{', '.join(map(str, AVAILABLE_YEARS))}。"

    if is_unsupported_question(query):
        return f"我目前只分析你上傳的球員數據。你可以直接問 {year} 的排行、球員數值或球員分析。"

    metric = extract_metric(query)
    found_player = find_player(query)
    top_n = extract_top_n(query)

    if metric is not None and found_player is None and top_n is not None:
        return answer_ranking(metric, top_n, year=year)

    if found_player is not None and is_analysis_question(query):
        role, name = found_player
        return answer_player_analysis(role, name, year=year)

    if metric is not None and found_player is not None:
        role, name = found_player
        return answer_player_metric(role, name, metric, year=year)

    if metric is not None and found_player is None:
        return f"你可以直接問：{year}前5名{metric['label']}、{year}{metric['label']}第一名是誰，或某位球員的 {metric['label']}。"

    if found_player is not None:
        role, name = found_player
        return f"你想看 {name} 的哪個指標？例如：{year} {name} 的 HR、OPS、ERA，或問 {name} 值不值得選。"

    return f"請直接問 {year} 的排行、球員數值或球員分析，例如：{year}全壘打王是誰、{year}前5名OPS打者、{year}前5名ERA投手。"

def chatbot_reply(query):
    try:
        return answer_question(query)
    except Exception as e:
        return f"系統發生錯誤：{e}"

app = Flask(__name__)

LINE_CHANNEL_SECRET = os.environ["LINE_CHANNEL_SECRET"]
LINE_CHANNEL_ACCESS_TOKEN = os.environ["LINE_CHANNEL_ACCESS_TOKEN"]

def verify_signature(body: bytes, signature: str) -> bool:
    digest = hmac.new(
        LINE_CHANNEL_SECRET.encode("utf-8"),
        body,
        hashlib.sha256
    ).digest()
    expected_signature = base64.b64encode(digest).decode("utf-8")
    return hmac.compare_digest(expected_signature, signature or "")

def reply_message(reply_token: str, text: str):
    url = "https://api.line.me/v2/bot/message/reply"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LINE_CHANNEL_ACCESS_TOKEN}"
    }
    payload = {
        "replyToken": reply_token,
        "messages": [
            {
                "type": "text",
                "text": str(text)[:5000]
            }
        ]
    }
    r = requests.post(url, headers=headers, json=payload, timeout=10)
    r.raise_for_status()

@app.route("/", methods=["GET"])
def home():
    return "LINE Bot is running", 200

@app.route("/callback", methods=["POST"])
def callback():
    body = request.get_data()
    signature = request.headers.get("X-Line-Signature", "")

    if not verify_signature(body, signature):
        abort(400)

    data = json.loads(body.decode("utf-8"))

    for event in data.get("events", []):
        if event.get("type") != "message":
            continue
        if event.get("message", {}).get("type") != "text":
            continue

        user_text = event["message"]["text"]
        reply_token = event["replyToken"]

        reply_text = chatbot_reply(user_text)
        reply_message(reply_token, reply_text)

    return "OK", 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
